from Credentials import Credentials

from User import User

def main():
    print("Welcome to password locker app")
    firstname = input("What is your firstname? ")
    lastname = input("What is your last name? ")
    email = input("What is your email address: ")

    print("Use these short codes to choose your service: ")
    print("---------------------")
    print("Password Locker")
    print("---------------------")
    print("1. Save username and password")
    print("2. create new username and autogenerated password")
    print("3. create new username and manually generated password")
    print("4. View stored username and password")
    print("5. Delete credetials account ")
    print("6. Exit")
    print("---------------------")
    option = int(input("Enter your choice: "))

    while option:
        if option == 1:
            print("New Username")
            input("Write your username: ")
            input( "Write your password ")
            print('Your name is {firstname} {lastname} and email is {email}')
            save_user(new_user)
            print('\n')
            print(f"New user {firstname} {lastname} created")
            print('\n')
            
        elif option == 2:
            create_cred()
        elif option == 3:
            createNamePasswordManual()
        elif option == 4:
            viewNamePassword()
        elif option == 5:
            delNamePassword()
            break
        else:
            print("Invalid Option")
            print("-------------")
            option = int(input("Enter option:"))

            print("Exiting...")
            print("---------------------")

if __name__ == "__main__":
    main()






